project_id = "iwaruroumrowiinwwntz"

[functions.run-question]
verify_jwt = false

[functions.apify-collect]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.filter-relevance]
verify_jwt = false

[functions.optimize-queries]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false
